/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import back.BusquedaRecursiva;

/**
 *
 * @author Ing-Sis
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());
    private int[] vector;
    private BusquedaRecursiva busqueda;
    private javax.swing.JPopupMenu menuTamanio;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        // 1. Manejo del botón de generar vector
        for (java.awt.event.ActionListener al : jButtonVector.getActionListeners()) {
            jButtonVector.removeActionListener(al);
        }

        jButtonVector.addActionListener(evt -> {
            String entrada = javax.swing.JOptionPane.showInputDialog(
                this, 
                "Ingrese el tamaño del vector:", 
                "Tamaño del Vector", 
                javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (entrada != null && !entrada.trim().isEmpty()) {
                try {
                    int tamano = Integer.parseInt(entrada.trim());

                    if (tamano > 0) {
                        busqueda = new BusquedaRecursiva(tamano);
                        vector = busqueda.retornarVector();
                        imprimirVector(vector, jPanelVector);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número mayor a 0.");
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número entero válido.");
                }
            }
        });

        // 2. Conectar el evento del botón Binaria (soluciona que no haga nada)
        for (java.awt.event.ActionListener al : jButtonBinaria.getActionListeners()) {
            jButtonBinaria.removeActionListener(al);
        }
        jButtonBinaria.addActionListener(this::jButtonBinariaActionPerformed);
    }
    private void imprimirVector(int[] vector, javax.swing.JPanel panel){
    panel.removeAll();
    panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 8));
    
    if (panel.getParent() != null) {
        int anchoDisponible = panel.getParent().getWidth();
        if (anchoDisponible > 0) {
            // Calculamos el alto según la cantidad de elementos para que el Scroll funcione
            int elementosPorFila = Math.max(1, (anchoDisponible - 16) / (40 + 8));
            int filas = (int) Math.ceil((double) vector.length / elementosPorFila);
            int altoRequerido = filas * (40 + 8) + 16;
            
            panel.setPreferredSize(new java.awt.Dimension(anchoDisponible - 20, altoRequerido));
        }
    }
    
    for (int i = 0; i < vector.length; i++) {
        javax.swing.JLabel lblNumero = new javax.swing.JLabel();
        lblNumero.setText(String.valueOf(vector[i]));
        lblNumero.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        
        // Formato visual de celda/casilla
        lblNumero.setPreferredSize(new java.awt.Dimension(40, 40));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setOpaque(true);
        lblNumero.setBackground(java.awt.Color.WHITE);
        lblNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 1));
        
        panel.add(lblNumero);
    }
    
    panel.revalidate();
    panel.repaint(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jButtonSecuencial = new javax.swing.JButton();
        jTitulo = new javax.swing.JLabel();
        jButtonIndice = new javax.swing.JButton();
        jButtonBinaria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonVector = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelVector = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(231, 231, 231));

        jButtonSecuencial.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSecuencial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSecuencial.setText("Secuencial");
        jButtonSecuencial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSecuencial.addActionListener(this::jButtonSecuencialActionPerformed);

        jTitulo.setBackground(new java.awt.Color(0, 255, 255));
        jTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/docuroreborn.png"))); // NOI18N
        jTitulo.setText("Busquedas Recursivas");
        jTitulo.setOpaque(true);
        jTitulo.setPreferredSize(new java.awt.Dimension(700, 500));

        jButtonIndice.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIndice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIndice.setText("Indice");
        jButtonIndice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIndice.addActionListener(this::jButtonIndiceActionPerformed);

        jButtonBinaria.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBinaria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBinaria.setText("Binaria");
        jButtonBinaria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Busquedas:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Generar vector:");

        jButtonVector.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVector.setText("Generar");
        jButtonVector.setToolTipText("");
        jButtonVector.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Vector:");

        jPanelVector.setBackground(new java.awt.Color(224, 224, 224));
        jPanelVector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelVectorLayout = new javax.swing.GroupLayout(jPanelVector);
        jPanelVector.setLayout(jPanelVectorLayout);
        jPanelVectorLayout.setHorizontalGroup(
            jPanelVectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelVectorLayout.setVerticalGroup(
            jPanelVectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelVector);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIndice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButtonVector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSecuencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecuencialActionPerformed
        // TODO add your handling code here:
        // 1. Validar que el vector ya haya sido generado
        if (vector == null || vector.length == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debe generar un vector.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Pedir el número a buscar
        String entrada = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Ingrese el número que desea buscar:", 
            "Búsqueda Secuencial", 
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 3. Procesar si el usuario ingresó algo
        if (entrada != null && !entrada.trim().isEmpty()) {
            int valorABuscar = Integer.parseInt(entrada.trim());

            // 4. Llamar a tu método recursivo arrancando desde el índice 0
            boolean encontrado = busqueda.secuencial(vector, 0, valorABuscar);

            // 5. Mostrar el mensaje con el resultado
            if (encontrado) {
                javax.swing.JOptionPane.showMessageDialog(
                    this, 
                    "¡El número " + valorABuscar + " SÍ se encuentra en el vector!", 
                    "Resultado", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this, 
                    "El número " + valorABuscar + " NO se encuentra en el vector.", 
                    "Resultado", 
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
                
    }//GEN-LAST:event_jButtonSecuencialActionPerformed

    private void jButtonIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndiceActionPerformed
        // TODO add your handling code here:
        if (vector == null || vector.length == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Primero debe generar un vector.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String entrada = javax.swing.JOptionPane.showInputDialog(
        this, 
        "Ingrese el número para consultar su índice:", 
        "Búsqueda por Índice", 
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (entrada != null && !entrada.trim().isEmpty()) {
        int valorABuscar = Integer.parseInt(entrada.trim());

        // La búsqueda mantiene la lógica interna iniciando en 0
        int posicion = busqueda.buscarIndice(vector, 0, valorABuscar);

        if (posicion != -1) {
            // Le sumamos 1 a 'posicion' para mostrar la numeración del usuario (1, 2, 3...)
            int posicionUsuario = posicion + 1;

            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "El número " + valorABuscar + " se encuentra en la posición: " + posicionUsuario, 
                "Resultado", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "El número " + valorABuscar + " NO se encuentra en el vector.", 
                "Resultado", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
}                                            

    private void jButtonBinariaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if (vector == null || vector.length == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Primero debe generar un vector.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Opcional pero recomendado: Asegurar que el vector esté ordenado para la búsqueda binaria
    java.util.Arrays.sort(vector);
    imprimirVector(vector, jPanelVector); // Vuelve a dibujar el vector ya ordenado en pantalla

    String entrada = javax.swing.JOptionPane.showInputDialog(
        this, 
        "Ingrese el número a buscar (Búsqueda Binaria):", 
        "Búsqueda Binaria", 
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (entrada != null && !entrada.trim().isEmpty()) {
        try {
            int valorABuscar = Integer.parseInt(entrada.trim());

            // Llamada al método recursivo de búsqueda binaria
            // inicio = 0, fin = vector.length - 1
            int posicion = busqueda.buscarBinaria(vector, 0, vector.length - 1, valorABuscar);

            if (posicion != -1) {
                // Le sumamos 1 para mostrar el índice iniciando desde 1
                int posicionUsuario = posicion + 1;

                javax.swing.JOptionPane.showMessageDialog(
                    this, 
                    "¡Encontrado! El número " + valorABuscar + " está en la posición: " + posicionUsuario, 
                    "Búsqueda Binaria - Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this, 
                    "El número " + valorABuscar + " NO se encuentra en el vector.", 
                    "Búsqueda Binaria - Resultado", 
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número entero válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
                                               

    private void jButtonVectorActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Manejado en el constructor
    }                                             

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }//GEN-LAST:event_jButtonIndiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBinaria;
    private javax.swing.JButton jButtonIndice;
    private javax.swing.JButton jButtonSecuencial;
    private javax.swing.JButton jButtonVector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelVector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitulo;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
